name: gitjournal
version: 1.83.0
summary: Note taking integrated with Git
description: Note taking integrated with Git

confinement: strict
base: core22
grade: stable

slots:
  dbus-gitjournal:
    interface: dbus
    bus: session
    name: io.gitjournal.gitjournal

apps:
  gitjournal:
    command: bin/gitjournal
    extensions: [gnome]
    plugs:
    - desktop-launch
    - network
    - network-manager
    - home
    - ssh-keys
    slots:
      - dbus-gitjournal

parts:
  gitjournal:
    source: .
    plugin: flutter
    stage-packages:
      - git
      - openssh-client
      - zenity

